Bug 2019162 [wpt PR 58026] - [wptrunner] Coerce script timeout to integer for non-wdspec tests, a=testonly
Automatic update from web-platform-tests
[wptrunner] Coerce script timeout to integer for non-wdspec tests (#58026)

https://crrev.com/c/7522226 seems to have caused Chrome on iOS results
to disappear from wpt.fyi because the final timeout is [fractional]:

```
webdriver.error.InvalidArgumentException: invalid argument (500): Timeouts must be non-negative integers
```

This can be replicated with the right `wpt run --timeout-multiplier`, so
avoid fractional timeouts in general. The spec for "Set Timeouts" isn't
clear on how they should be handled (w3c/webdriver#1949), but the de
facto behavior is to return "invalid argument".

Note that the WebDriver client can still send fractional timeouts to
test invalid values.

[fractional]: https://chromium-swarm.appspot.com/task?id=7673a57e106bad10&w=true
--

wpt-commits: fcfb8ff3fb11891f472c0c1d448564d6bb4e14f7
wpt-pr: 58026